// const JWT_USER_PASSWORD = process.env.JWT_USER_PASSWORD;
// const JWT_ADMIN_PASSWORD = process.env.JWT_ADMIN_PASSWORD;
const JWT_ADMIN_PASSWORD = "lololol@123231";
const JWT_USER_PASSWORD = "LMAOLMAojfns@238y34981";

module.exports = {
  JWT_ADMIN_PASSWORD,
  JWT_USER_PASSWORD,
};
